DIRECTORY:
  dataset: train
  #{DATA_DIR}/train

TRAINER :
  model: denov2
  optimizer: adam
  learning_rate: 5.0e-4
  loss: bce
  metric:
    - accuracy
    - f1macro
  n_epochs: 30
  early_stopping_target: val_accuracy
  early_stopping_patience: 2
  early_stopping_mode: max
  amp: False
  gpu: 0
  seed: 42
  

MODEL:
  effnet:
    backbone: efficientnet_b0
    n_out: 1
    is_sigmoid: True
  vit:
    backbone: vit_large_patch14_clip_224.openai_ft_in12k_in1k
    n_out: 1
    is_sigmoid: True
  denov2:
    backbone: vit_base_patch14_dinov2.lvd142m
    n_out: 1
    is_sigmoid: True
    freeze_ratio: 0.79

DATASET:
  val_size : 0.999

DATALOADER:
  batch_size: 4
  num_workers: 0
  shuffle: True
  pin_memory: True
  drop_last: True

LOGGER:
  debug : False
  wandb: False
  logging_interval: 100
  plot:
    - loss
    - accuracy
    - f1macro
    - elapsed_time

